// Generated by CoffeeScript 2.7.0
(function() {
  var cpu, global, hotswap, reset, run, step, undo;

  if (typeof global === "undefined" || global === null) {
    global = window;
  }

  cpu = new SimpleCPU(SSMInstructionSet);

  hotswap = function() {
    var code;
    code = Parser.parse(View.getSrc());
    return cpu.load(code);
  };

  reset = function() {
    cpu.reset();
    return View.update(cpu);
  };

  step = function() {
    hotswap();
    cpu.step();
    return View.update(cpu);
  };

  undo = function() {
    cpu.undo();
    return View.update(cpu);
  };

  run = function() {
    hotswap();
    cpu.run();
    return View.update(cpu);
  };

  View.addButton("rewind", reset);

  View.addButton("step-back", undo);

  View.addButton("step", step);

  View.addButton("fast-forward", run);

  $(document).bind('keydown', 'ctrl+]', step);

  View.sourceChanged = function() {
    hotswap();
    return View.update(cpu);
  };

  View.sourceChanged();

  global._ = {cpu};

}).call(this);

//# sourceMappingURL=main.js.map
