// Generated by CoffeeScript 1.6.2
(function() {
  var cpu, global, hotswap, reset;

  if (typeof global === "undefined" || global === null) {
    global = window;
  }

  cpu = new SimpleCPU(SSMInstructionSet);

  hotswap = function() {
    var code;

    code = Parser.parse(View.getSrc());
    return cpu.load(code);
  };

  reset = function() {
    return cpu.reset();
  };

  View.addButton("reset", function() {
    cpu.reset();
    return View.update(cpu);
  });

  View.addButton("step", function() {
    hotswap();
    cpu.step();
    return View.update(cpu);
  });

  View.addButton("run", function() {
    hotswap();
    cpu.run();
    return View.update(cpu);
  });

  View.sourceChanged = function() {
    hotswap();
    return View.update(cpu);
  };

  View.sourceChanged();

  global._ = {
    cpu: cpu
  };

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
